### ISSUE TITLE
Schematic?

### ISSUE THREAD

**Issue by dwaq** [piotrb5e3/AT89C2051_programmer#1]
Do you have a schematic for your programmer? I'm most interested in how you switched between the 12V/5V/0V on the RST pin. Even a sketch of this part of the circuit would help me out. Thanks in advance!

**Comment by piotrb5e3** [comment]
Added kicad project with the schematic + rendered PDF. The optocoupler could also be a transistor-output one.

**Comment by namebee** [comment]
Sorry for reviving such an old project, but could you explain the circuit to me? I've been trying to get into electronics and I'm really struggling to figure out how you're switching between those voltages. I'm especially struggling with the diode part.
