### ISSUE TITLE
I'm getting error massage

### ISSUE THREAD

**Issue by rashhad** [piotrb5e3/AT89C2051_programmer#4]
Hi, I'm getting the following error messege when tring to upload hello.ihx file:
```
C:\Users\Rashad\OneDrive\Desktop\at89c2051\hello-8051>at89overlord -p COM3 -f hello.ihx
# Initializing the programmer...
# Initialized!
# Confirming chip ID...
Traceback (most recent call last):
  File "C:\Users\Rashad\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Rashad\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Rashad\AppData\Local\Programs\Python\Python310\Scripts\at89overlord.exe\__main__.py", line 7, in <module>
  File "C:\Users\Rashad\AppData\Local\Programs\Python\Python310\lib\site-packages\at89overlord\at89runner.py", line 54, in main
    comm.do_confirm_signature()
  File "C:\Users\Rashad\AppData\Local\Programs\Python\Python310\lib\site-packages\at89overlord\at89comm.py", line 113, in do_confirm_signature
    raise AT89CommException(errmsg)
at89overlord.at89comm.AT89CommException: Incorrect chip signature. Expected: 1E,21 Got: FE,FE
```

I'm also using bc557 pnp trnasistor in the place of TLP222A. Please see the attached image. The complete arragement is on solderless breadboard.
<img width="223" alt="circuit" src="https://github.com/user-attachments/assets/a0684b92-837d-4b05-8921-92689085fe18">

**Comment by rashhad** [comment]
Hi again! I made the setup on perfboard. I found some mistake and I added an optocoupler to my new circuit. I'm attaching the diagram. but still getting the same error message. Except the last line:
`Incorrect chip signature. Expected: 1E,21 Got: FE,FE`
becomes
`Incorrect chip signature. Expected: 1E,21 Got: FC,00` 
and
`Incorrect chip signature. Expected: 1E,21 Got: 00,FC`
and 
`Incorrect chip signature. Expected: 1E,21 Got: FC,FC`
alternatively.
I'm using windows 11, python 3.10.4

Updated 12v reset diagram:
![circuit (1)](https://github.com/user-attachments/assets/7b50d4b0-26bb-4d23-83ae-ccd565eebbff)

**Comment by piotrb5e3** [comment]
Hi,
In your first setup, the AT89_RST pin would never be pulled down to 0V, because the A1 pin can't go to a voltage high enough to turn off the transistor.

In your second setup, you could try measuring the voltage on AT89_RST when the optocoupler is turned on and off. I think it may also have some issues there. Maybe adding a pull-up resistor between the base and emitter of the transistor would help, but you'd have to check that yourself.

To me, the error message you are getting points to the chip not being reset/put into programming mode correctly. I used the solid-state relay component (TLP222A) specifically not to worry about transistors and voltages.

**Comment by rashhad** [comment]
Thank you for the reply. On the first try, AT89C2051 IC got damaged. I did a mistake with the transistor. That might be the reason.  After making the second circuit on perfboard and replaced the IC with a new one, the code was successfully uploaded.
Thank you again for making this repo.

**Comment by rashhad** [comment]
> Hi, In your first setup, the AT89_RST pin would never be pulled down to 0V, because the A1 pin can't go to a voltage high enough to turn off the transistor.
> 
Yes I understood. And the worrying part was the 12V supply directly connected to arduino A1 pin which is 5V tolerant. I didn’t notice it until I failed at the first time and review the circuit. Fortunately the pin A1 was still okay.

> In your second setup, you could try measuring the voltage on AT89_RST when the optocoupler is turned on and off. I think it may also have some issues there. Maybe adding a pull-up resistor between the base and emitter of the transistor would help, but you'd have to check that yourself.
> 
I did this and found it operating normally. Than I replaced the IC with new one.

**Comment by piotrb5e3** [comment]
Glad to know it works for you
